In [2]:
import numpy as np

In [3]:
c = 7
d = 7.0


In [4]:
c == d

True

In [5]:
type(c)

int

In [6]:
type(d)

float

In [7]:
for i in range(c):
    print(i)

0
1
2
3
4
5
6


In [8]:
for i in range(d):
    print(i)

TypeError: 'float' object cannot be interpreted as an integer

In [9]:
first_name = 'jack'
last_name = 'yao'
type(first_name)

str

In [10]:
first_name + last_name

'jackyao'

In [12]:
first_name * 3

'jackjackjack'

In [13]:
%whos

Variable     Type      Data/Info
--------------------------------
c            int       7
d            float     7.0
first_name   str       jack
i            int       6
last_name    str       yao
np           module    <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>


In [14]:
s1 = '4'
s2 = '4.7'
n1 = int(s1)
n2 = float(s2)

In [15]:
n3 = 5
n4 = 5.0
n5 = str(n3)
n6 = str(5.0)

In [16]:
%whos


Variable     Type      Data/Info
--------------------------------
c            int       7
d            float     7.0
first_name   str       jack
i            int       6
last_name    str       yao
n1           int       4
n2           float     4.7
n3           int       5
n4           float     5.0
n5           str       5
n6           str       5.0
np           module    <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
s1           str       4
s2           str       4.7


In [17]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [18]:
a = [1,'2',3]

In [19]:
a

[1, '2', 3]

In [20]:
b = [1,[2,3], 4]

In [21]:
b

[1, [2, 3], 4]

In [22]:
a + b

[1, '2', 3, 1, [2, 3], 4]

In [23]:
a - b

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [24]:
a * 3

[1, '2', 3, 1, '2', 3, 1, '2', 3]

In [25]:
b * 3

[1, [2, 3], 4, 1, [2, 3], 4, 1, [2, 3], 4]

In [26]:
a_np = np.array(a)

In [27]:
a_np

array(['1', '2', '3'], dtype='<U21')

In [30]:
print(type(a_np))

<class 'numpy.ndarray'>


In [31]:
a_np

array(['1', '2', '3'], dtype='<U21')

In [32]:
print(a_np)

['1' '2' '3']


In [33]:
a_np * 3

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U21'), dtype('int64')) -> None

In [34]:
a_np

array(['1', '2', '3'], dtype='<U21')

In [35]:
a

[1, '2', 3]

In [36]:
c = [1,2,3]
c_np = np.array(c)

In [37]:
c_np * 3

array([3, 6, 9])

In [38]:
c_np

array([1, 2, 3])

In [39]:
c_np + [4]

array([5, 6, 7])

In [40]:
c_np + 4

array([5, 6, 7])

In [41]:
c_np

array([1, 2, 3])

In [43]:
c_np + 4

array([5, 6, 7])

In [44]:
d = [3,['3','4','5'],5,5, [4,5,6]]

In [45]:
d

[3, ['3', '4', '5'], 5, 5, [4, 5, 6]]

In [49]:
for i in range(len(d)):
    print(f'List element {i} is {d[i]} and is of type {type(d[i])}')

List element 0 is 3 and is of type <class 'int'>
List element 1 is ['3', '4', '5'] and is of type <class 'list'>
List element 2 is 5 and is of type <class 'int'>
List element 3 is 5 and is of type <class 'int'>
List element 4 is [4, 5, 6] and is of type <class 'list'>


In [50]:
for k,v in enumerate(d):
    print(f'List element {k} is {v} and is of type {type(v)}')

List element 0 is 3 and is of type <class 'int'>
List element 1 is ['3', '4', '5'] and is of type <class 'list'>
List element 2 is 5 and is of type <class 'int'>
List element 3 is 5 and is of type <class 'int'>
List element 4 is [4, 5, 6] and is of type <class 'list'>


In [56]:
for k,v in enumerate(d):
    t = str(type(v))[8:-2]
    print(f'List element {k} is {v} and is of type {t}')

List element 0 is 3 and is of type int
List element 1 is ['3', '4', '5'] and is of type list
List element 2 is 5 and is of type int
List element 3 is 5 and is of type int
List element 4 is [4, 5, 6] and is of type list


In [57]:
for k,v in enumerate(d):
    t = str(type(v))[8:]
    apost = t.find("'")
    print(f'List element {k} is {v} and is of type {t[:apost]}')

List element 0 is 3 and is of type int
List element 1 is ['3', '4', '5'] and is of type list
List element 2 is 5 and is of type int
List element 3 is 5 and is of type int
List element 4 is [4, 5, 6] and is of type list
