In [2]:
import sympy as sym
from IPython.display import display,Math
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp

In [6]:
A = np.random.randn(14,10)
B = np.random.randn(14,10)
C = np.random.randn(10,14)
np.shape(C@B)
np.shape(B@C)


(14, 14)

In [22]:
def metrix_multiplication(A,B):
    size_a = np.shape(A)
    size_b = np.shape(B)
    print(size_a)
    print(size_b)
    if size_a[1] != size_b[0]:
        raise ValueError('Inner dimensions don\'t match')
    
    C = np.zeros((size_a[0],size_b[1]))
    for i in range(size_a[0]):
        for j in range(size_b[1]):
            C[i,j] = np.dot(A[i,:],B[:,j])

    return C        
    

In [23]:
A = np.random.randn(4,6)
B = np.random.randn(6,4)
C = metrix_multiplication(A,B)

(4, 6)
(6, 4)


In [24]:
D= A@B

In [29]:
C

array([[ 1.17530752,  4.6380657 ,  0.69308287,  2.33371937],
       [ 0.3492802 ,  1.69394212, -0.1901307 ,  1.33779183],
       [ 0.2936515 , -0.09119866, -0.93040695,  0.31238678],
       [ 0.12133899, -0.82554103, -3.16651814,  0.43940737]])

In [26]:
C

array([[ 1.17530752,  4.6380657 ,  0.69308287,  2.33371937],
       [ 0.3492802 ,  1.69394212, -0.1901307 ,  1.33779183],
       [ 0.2936515 , -0.09119866, -0.93040695,  0.31238678],
       [ 0.12133899, -0.82554103, -3.16651814,  0.43940737]])

In [30]:
D

array([[ 1.17530752,  4.6380657 ,  0.69308287,  2.33371937],
       [ 0.3492802 ,  1.69394212, -0.1901307 ,  1.33779183],
       [ 0.2936515 , -0.09119866, -0.93040695,  0.31238678],
       [ 0.12133899, -0.82554103, -3.16651814,  0.43940737]])

In [38]:
C[0]

array([1.17530752, 4.6380657 , 0.69308287, 2.33371937])

In [37]:
D[0]

array([1.17530752, 4.6380657 , 0.69308287, 2.33371937])

In [44]:
C[0] == D[0]

array([False, False,  True, False])

In [45]:
C[0][0]

1.1753075178428103

In [46]:
D[0][0]

1.1753075178428105

In [47]:
C - D

array([[-2.22044605e-16,  8.88178420e-16,  0.00000000e+00,
        -4.44089210e-16],
       [-5.55111512e-17,  0.00000000e+00,  2.77555756e-17,
         0.00000000e+00],
       [ 1.11022302e-16, -5.55111512e-17,  0.00000000e+00,
         5.55111512e-17],
       [ 5.55111512e-17,  1.11022302e-16,  4.44089210e-16,
         5.55111512e-17]])