In [1]:
import sympy as sym
import numpy as np
from IPython.display import display, Math

In [4]:
A = np.array([[1,2],[3,4]])

In [5]:
A

array([[1, 2],
       [3, 4]])

In [10]:
display(Math(sym.latex(sym.sympify(A))))

<IPython.core.display.Math object>

In [11]:
sym.sympify(A)

[[1, 2], [3, 4]]

In [12]:
A

array([[1, 2],
       [3, 4]])

In [25]:
mat = np.zeros([4,6])

In [26]:
mat

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
mat[0,1] = 2

In [28]:
mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

mat[2,3] = 7

In [31]:
mat[2,3] = 7

In [32]:
mat[2,3]

7.0

In [33]:
mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
mat[2,4] = 8

In [35]:
mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 7., 8., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [38]:
num_range = range(0,2)
for row_i in num_range:
    for col_i in num_range:
        mat[row_i, col_i] = (-1) ** (row_i + col_i)

In [39]:
mat

array([[ 1., -1.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  7.,  8.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [40]:
num_range = range(0,4)
for row_i in num_range:
    for col_i in num_range:
        mat[row_i, col_i] = (-1) ** (row_i + col_i)

In [41]:
mat

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  8.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

In [42]:
sym.sympify(mat)

[[1.0, -1.0, 1.0, -1.0, 0.0, 0.0], [-1.0, 1.0, -1.0, 1.0, 0.0, 0.0], [1.0, -1.0, 1.0, -1.0, 8.0, 0.0], [-1.0, 1.0, -1.0, 1.0, 0.0, 0.0]]

In [44]:
x,y = sym.symbols('x,y')
fxy = (4+x)*(2-y)
xyset = range(0,3)
outmat = np.zeros([len(xyset), len(xyset)])


In [45]:
outmat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [49]:
for row_i in xyset:
    for col_i in xyset:
        outmat[row_i, col_i] = fxy.subs({x: row_i,y: col_i})

In [50]:
outmat

array([[ 8.,  4.,  0.],
       [10.,  5.,  0.],
       [12.,  6.,  0.]])

In [51]:
sym.sympify(outmat)

[[8.0, 4.0, 0.0], [10.0, 5.0, 0.0], [12.0, 6.0, 0.0]]

In [60]:
mat_mult = np.zeros([10,10],dtype=int)

In [61]:
mat_mult

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [55]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [62]:
for i in range(1, 11):
    for j in range(1,11):
        mat_mult[i-1][j-1] = i*j


In [63]:
mat_mult

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [64]:
sym.sympify(mat_mult)

[[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [2, 4, 6, 8, 10, 12, 14, 16, 18, 20], [3, 6, 9, 12, 15, 18, 21, 24, 27, 30], [4, 8, 12, 16, 20, 24, 28, 32, 36, 40], [5, 10, 15, 20, 25, 30, 35, 40, 45, 50], [6, 12, 18, 24, 30, 36, 42, 48, 54, 60], [7, 14, 21, 28, 35, 42, 49, 56, 63, 70], [8, 16, 24, 32, 40, 48, 56, 64, 72, 80], [9, 18, 27, 36, 45, 54, 63, 72, 81, 90], [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]]