In [1]:
import sympy as sym
import numpy as np
from IPython.display import display, Math

In [4]:
A = np.array([[1,2],[3,4]])

In [5]:
A

array([[1, 2],
       [3, 4]])

In [10]:
display(Math(sym.latex(sym.sympify(A))))

<IPython.core.display.Math object>

In [11]:
sym.sympify(A)

[[1, 2], [3, 4]]

In [12]:
A

array([[1, 2],
       [3, 4]])

In [25]:
mat = np.zeros([4,6])

In [26]:
mat

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
mat[0,1] = 2

In [28]:
mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

mat[2,3] = 7

In [31]:
mat[2,3] = 7

In [32]:
mat[2,3]

7.0

In [33]:
mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
mat[2,4] = 8

In [35]:
mat

array([[0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 7., 8., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [38]:
num_range = range(0,2)
for row_i in num_range:
    for col_i in num_range:
        mat[row_i, col_i] = (-1) ** (row_i + col_i)

In [39]:
mat

array([[ 1., -1.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  7.,  8.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [40]:
num_range = range(0,4)
for row_i in num_range:
    for col_i in num_range:
        mat[row_i, col_i] = (-1) ** (row_i + col_i)

In [41]:
mat

array([[ 1., -1.,  1., -1.,  0.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.],
       [ 1., -1.,  1., -1.,  8.,  0.],
       [-1.,  1., -1.,  1.,  0.,  0.]])

In [42]:
sym.sympify(mat)

[[1.0, -1.0, 1.0, -1.0, 0.0, 0.0], [-1.0, 1.0, -1.0, 1.0, 0.0, 0.0], [1.0, -1.0, 1.0, -1.0, 8.0, 0.0], [-1.0, 1.0, -1.0, 1.0, 0.0, 0.0]]

In [44]:
x,y = sym.symbols('x,y')
fxy = (4+x)*(2-y)
xyset = range(0,3)
outmat = np.zeros([len(xyset), len(xyset)])


In [45]:
outmat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
for row_i in xyset:
    for col_i in xyset:
        outmat[row_i, col_i] = (4+row_i)*(2-col_i)

In [48]:
outmat

array([[ 8.,  4.,  0.],
       [10.,  5.,  0.],
       [12.,  6.,  0.]])